include ../../makefile.inc

pmtxhfiles=TieAliases.txh TieGeneric.txh TieGroup.txh TieHost.txh \
TieNamed.txh TieNet.txh TiePh.txh TieProto.txh TieServ.txh TieShadow.txh \
TieUser.txh Cfgfile.txh TieRCService.txh CfgArgs.txh filever.txh TieRsrc.txh

install:

all: $(pmtxhfiles)
