include ../../makefile.inc

pmtexfiles=TieAliases.tex TieGeneric.tex TieGroup.tex TieHost.tex \
TieNamed.tex TieNet.tex TiePh.tex TieProto.tex TieServ.tex TieShadow.tex \
TieUser.tex Cfgfile.tex TieRCService.tex CfgArgs.tex filever.tex

install:

all: $(pmtexfiles)
